[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 10000

[browser]
gatherUsageStats = false

[theme]
primaryColor="#4F46E5"
backgroundColor="#F9FAFB"
secondaryBackgroundColor="#FFFFFF"
textColor="#111827"
font="sans serif"